---
abstract: ~
author:
  - 'Sergey Aleynikov <sergey.aleynikov@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Devel-PrettyTrace
no_index:
  directory:
    - inc
    - t
requires:
  Exporter: 0
  perl: 5.6.0
  Data::Printer: 0.19
  parent: 0
  List::MoreUtils: 0
resources:
  license: http://opensource.org/licenses/bsd-license.php
version: 0.04
